In [1]:
from google.colab import files
files.upload()

Saving mobile_ads.csv to mobile_ads.csv


{'mobile_ads.csv': b'User ID,Gender,Age,EstimatedSalary,Purchased\n15624510,Male,19,19000,0\n15810944,Male,35,20000,0\n15668575,Female,26,43000,0\n15603246,Female,27,57000,0\n15804002,Male,19,76000,0\n15728773,Male,27,58000,0\n15598044,Female,27,84000,0\n15694829,Female,32,150000,1\n15600575,Male,25,33000,0\n15727311,Female,35,65000,0\n15570769,Female,26,80000,0\n15606274,Female,26,52000,0\n15746139,Male,20,86000,0\n15704987,Male,32,18000,0\n15628972,Male,18,82000,0\n15697686,Male,29,80000,0\n15733883,Male,47,25000,1\n15617482,Male,45,26000,1\n15704583,Male,46,28000,1\n15621083,Female,48,29000,1\n15649487,Male,45,22000,1\n15736760,Female,47,49000,1\n15714658,Male,48,41000,1\n15599081,Female,45,22000,1\n15705113,Male,46,23000,1\n15631159,Male,47,20000,1\n15792818,Male,49,28000,1\n15633531,Female,47,30000,1\n15744529,Male,29,43000,0\n15669656,Male,31,18000,0\n15581198,Male,31,74000,0\n15729054,Female,27,137000,1\n15573452,Female,21,16000,0\n15776733,Female,28,44000,0\n15724858,Male,27,90

In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from mlxtend.classifier import StackingClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from imblearn.over_sampling import SMOTE

In [3]:
data = pd.read_csv('mobile_ads.csv')
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [5]:
data.drop("User ID",axis = 1, inplace = True)
data.head()

Gender  Age  EstimatedSalary  Purchased
0    Male   19            19000          0
1    Male   35            20000          0
2  Female   26            43000          0
3  Female   27            57000          0
4    Male   19            76000          0

In [6]:
data.Gender.unique()

array(['Male', 'Female'], dtype=object)

In [8]:
data.Purchased.value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [10]:
encoder = LabelEncoder()
data['Gender'] = encoder.fit_transform(data['Gender'])
data.head()

Gender  Age  EstimatedSalary  Purchased
0       1   19            19000          0
1       1   35            20000          0
2       0   26            43000          0
3       0   27            57000          0
4       1   19            76000          0

In [11]:
X = data.drop('Purchased', axis=1)
y = data['Purchased']

In [12]:
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)

In [22]:
x_train, x_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=42)

In [23]:
logistic_model = LogisticRegression()
logistic_model.fit(x_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [24]:
y_pred = logistic_model.predict(x_test)

In [25]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.8737864077669902

Confusion Matrix:
 [[51  5]
 [ 8 39]]

Classification Report:
               precision    recall  f1-score   support

           0       0.86      0.91      0.89        56
           1       0.89      0.83      0.86        47

    accuracy                           0.87       103
   macro avg       0.88      0.87      0.87       103
weighted avg       0.87      0.87      0.87       103



In [26]:
decision_model = DecisionTreeClassifier()
decision_model.fit(x_train, y_train)

DecisionTreeClassifier()

In [27]:
y_pred = decision_model.predict(x_test)

In [28]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.9029126213592233

Confusion Matrix:
 [[48  8]
 [ 2 45]]

Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.86      0.91        56
           1       0.85      0.96      0.90        47

    accuracy                           0.90       103
   macro avg       0.90      0.91      0.90       103
weighted avg       0.91      0.90      0.90       103



In [30]:
random_model = RandomForestClassifier()
random_model.fit(x_train, y_train)

RandomForestClassifier()

In [31]:
y_pred = random_model.predict(x_test)

In [32]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.9029126213592233

Confusion Matrix:
 [[50  6]
 [ 4 43]]

Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.89      0.91        56
           1       0.88      0.91      0.90        47

    accuracy                           0.90       103
   macro avg       0.90      0.90      0.90       103
weighted avg       0.90      0.90      0.90       103



In [34]:
base_learners = [
    ('logistic', LogisticRegression()),
    ('decision', DecisionTreeClassifier()),
    ('random', RandomForestClassifier())
]
meta_model = DecisionTreeClassifier()
stacking_model = StackingClassifier(classifiers=[base_learner[1] for base_learner in base_learners], meta_classifier=meta_model)

In [35]:
stacking_model.fit(x_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


StackingClassifier(classifiers=[LogisticRegression(), DecisionTreeClassifier(),
                                RandomForestClassifier()],
                   meta_classifier=DecisionTreeClassifier())

In [36]:
y_pred = stacking_model.predict(x_test)

In [37]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.8737864077669902

Confusion Matrix:
 [[48  8]
 [ 5 42]]

Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.86      0.88        56
           1       0.84      0.89      0.87        47

    accuracy                           0.87       103
   macro avg       0.87      0.88      0.87       103
weighted avg       0.88      0.87      0.87       103

